// data/talents.js
export const talents = [
  {
    id: "1",
    name: "Michael Chen",
    title: "Electrical Engineering Student – UI/UX Enthusiast",
    university: "Boston University",
    location: "Boston, MA",
    image:
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-2.jpg",
    skills: ["UI Design", "Arduino", "3D Modeling", "React"],
    status: "Available",
    rating: 4.8,
    isTopTalent: false,
    categories: ["UI/UX Design", "Engineering"],
    about:
      "I'm a passionate Electrical Engineering student with a strong interest in UI/UX design. I combine my technical knowledge with creative design thinking to build intuitive and functional interfaces. I'm currently seeking opportunities to apply my skills in real-world projects.",
    interests: [
      "UI/UX Design",
      "Arduino Projects",
      "Mobile App Development",
      "3D Printing",
      "Photography",
    ],
    education: {
      school: "Boston University",
      degree: "Bachelor of Science in Electrical Engineering",
      years: "2021 - 2025",
    },
    email: "michael.chen@bu.edu",
  },
  {
    id: "2",
    name: "Sophia Williams",
    title: "Graphic Design Major – Brand Identity Specialist",
    university: "Rhode Island School of Design",
    location: "Providence, RI",
    image:
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-1.jpg",
    skills: ["Branding", "Illustration", "Typography", "Adobe Suite"],
    status: "Available",
    rating: 4.9,
    isTopTalent: true,
    categories: ["Graphic Design", "Branding"],
    about:
      "Creative graphic designer specializing in brand identity and visual communication. I help businesses tell their story through compelling visual design.",
    interests: [
      "Brand Design",
      "Typography",
      "Illustration",
      "Print Design",
      "Art Direction",
    ],
    education: {
      school: "Rhode Island School of Design",
      degree: "Bachelor of Fine Arts in Graphic Design",
      years: "2020 - 2024",
    },
    email: "sophia.williams@risd.edu",
  },
  {
    id: "3",
    name: "David Johnson",
    title: "Computer Science Student – Full Stack Developer",
    university: "MIT",
    location: "Cambridge, MA",
    image:
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-3.jpg",
    skills: ["React", "Node.js", "MongoDB", "AWS"],
    status: "Available",
    rating: 4.7,
    isTopTalent: false,
    categories: ["Web Development", "Software Engineering"],
    about:
      "Full-stack developer with experience in modern web technologies. I build scalable applications with clean, maintainable code.",
    interests: [
      "Web Development",
      "Cloud Computing",
      "Machine Learning",
      "Open Source",
      "Blockchain",
    ],
    education: {
      school: "MIT",
      degree: "Bachelor of Science in Computer Science",
      years: "2021 - 2025",
    },
    email: "david.johnson@mit.edu",
  },
  {
    id: "4",
    name: "Emma Rodriguez",
    title: "Marketing Student – Social Media Strategist",
    university: "New York University",
    location: "New York, NY",
    image:
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-5.jpg",
    skills: ["Content Creation", "Analytics", "Campaign Design"],
    status: "Available",
    rating: 4.6,
    isTopTalent: true,
    categories: ["Marketing", "Social Media"],
    about:
      "Digital marketing strategist with expertise in social media campaigns and content creation. I help brands connect with their audience through engaging content.",
    interests: [
      "Social Media Marketing",
      "Content Strategy",
      "Brand Management",
      "Digital Analytics",
      "Influencer Marketing",
    ],
    education: {
      school: "New York University",
      degree: "Bachelor of Business in Marketing",
      years: "2020 - 2024",
    },
    email: "emma.rodriguez@nyu.edu",
  },
  {
    id: "5",
    name: "James Wilson",
    title: "Film & Media Production – Cinematographer",
    university: "USC School of Cinematic Arts",
    location: "Los Angeles, CA",
    image:
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-4.jpg",
    skills: ["Video Editing", "Color Grading", "After Effects"],
    status: "Available",
    rating: 4.5,
    isTopTalent: false,
    categories: ["Video Production", "Cinematography"],
    about:
      "Cinematographer and video editor with a passion for visual storytelling. I create compelling video content for brands and filmmakers.",
    interests: [
      "Cinematography",
      "Video Production",
      "Color Grading",
      "Documentary Film",
      "Commercial Photography",
    ],
    education: {
      school: "USC School of Cinematic Arts",
      degree: "Bachelor of Fine Arts in Film Production",
      years: "2021 - 2025",
    },
    email: "james.wilson@usc.edu",
  },
  {
    id: "6",
    name: "Olivia Martinez",
    title: "Architecture Student – Sustainable Design",
    university: "Cornell University",
    location: "Ithaca, NY",
    image:
      "https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-6.jpg",
    skills: ["3D Modeling", "AutoCAD", "Revit", "SketchUp"],
    status: "Available",
    rating: 4.8,
    isTopTalent: true,
    categories: ["Architecture", "3D Modeling"],
    about:
      "Architecture student passionate about sustainable design and green building practices. I design spaces that are both beautiful and environmentally responsible.",
    interests: [
      "Sustainable Architecture",
      "Green Building",
      "Urban Planning",
      "3D Visualization",
      "Environmental Design",
    ],
    education: {
      school: "Cornell University",
      degree: "Bachelor of Architecture",
      years: "2020 - 2025",
    },
    email: "olivia.martinez@cornell.edu",
  },
];

export const categories = [
  "UI/UX Design",
  "Web Development",
  "Graphic Design",
  "Video Production",
  "3D Modeling",
  "Engineering",
  "Marketing",
  "Architecture",
  "Branding",
  "Software Engineering",
  "Social Media",
  "Cinematography",
];

export const universities = [
  "Boston University",
  "MIT",
  "Harvard University",
  "NYU",
  "Cornell University",
  "Rhode Island School of Design",
  "USC School of Cinematic Arts",
  "Stanford University",
  "Yale University",
  "Princeton University",
];
